name: h2oGPTe Agent Assistant

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created, edited]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  h2ogpte-agent-assistant:
    name: h2oGPTe Agent Assistant
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issues' && contains(github.event.issue.body, '@h2ogpte')) ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@h2ogpte')) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.body, '@h2ogpte')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@h2ogpte')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@h2ogpte'))

    steps:
      - name: h2oGPTe Agent Assistant
        id: h2ogpte-agent-assistant
        uses: h2oai/h2ogpte-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          h2ogpte_api_key: ${{ secrets.H2OGPTE_API_KEY }}
          h2ogpte_api_base: ${{ secrets.H2OGPTE_API_BASE }}
          github_api_url: https://github.com/santhosh1299/H2O-Wave_dashboard.git/api/v3
          github_server_url: https://github.com/santhosh1299/H2O-Wave_dashboard.git
          # h2oGPTe Configuration (optional)
          llm: "auto" # choose from: https://docs.h2o.ai/enterprise-h2ogpte/guide/models-section
          agent_max_turns: "auto" # agent_max_turns must be one of: {"auto", 5, 10, 15, 20}
          agent_accuracy: "standard" # agent_accuracy must be one of: {"quick", "basic", "standard", "maximum"}
          agent_total_timeout: 3600 # agent_total_timeout must be a positive integer in seconds
